### ISSUE TITLE
Significant performance degradation on multiple OAK-D units

### ISSUE THREAD

**Issue by manbehindthemadness** [luxonis/depthai-core#622]
Mentioned in Discord here: https://discord.com/channels/790680891252932659/799407361986658354/1035221653803765771

  I have been fighting an odd slowdown on an OAK-D Pro-W for the past few days. For reasons unknown at the time the RGB capture started to manifest almost a seconds lag/delay, and the mono cameras almost a additional second. I finally traced the issue all the way down to my applications depthai pipeline (v2.17.4.0/usb.SUPER). I was curious because I had tested this portion of the application rigorously with almost no delay time at all. So I pulled one of my dev OAK-D units out and ran the code there (v2.17.3.0/usb.HIGH), to my surprise the code ran as expected (30+ fps, almost no delay). 
  A few minutes later I am having a coffee and brainstorming on how to troubleshoot the issue when it occurs to me that I should get a video capture of the discrepancy and hit up Discord for some advice. I'm getting the experiment set up when I am shocked to discover that my dev OAK now has the same problem as my production unit. At this stage, I pulled out of my code completely and went back to the examples that I used to postulate my pipeline in the first-place: https://github.com/examples/StereoDepth/rgb_depth_aligned.py
Sure enough, the example code that ran perfectly days before now has **seconds** of delay and is running well under 10fps: 

https://user-images.githubusercontent.com/24589462/198377992-4f791d2f-f050-4a71-b474-c676e065135c.mp4

I noticed that a newer version of the software had been released so I updated both systems to 2.18.0.0 (no change).

My dev unit: 
![unknown](https://user-images.githubusercontent.com/24589462/198378485-e932bd58-3b70-44e2-bc14-5f73ccf99a85.png)

My production unit:
![unknown](https://user-images.githubusercontent.com/24589462/198378580-43beb655-9ed0-4e9f-a6ff-e1b09e2657e5.png)

Any help or advice would be much appreciated

**Comment by manbehindthemadness** [comment]
I think it's also important to mention that the delays seem to be incremental in nature. I see about 800-900ms delay in the RGB capture outputs; however, I see an **additional** delay in the mono cameras that appears to be the same: 
Subject moves in front of the camera, 900ms later RGB output, an additional 900ms mono output. These values seem to be the same as when I perform circular movements I can time them into thirds.

**Comment by manbehindthemadness** [comment]
NEW Info: So after experimenting all afternoon trying to figure out what on earth is going on I tried removing the OAK from the dev machine and plugging it into my macbook. I was greeted by the message: 
~~Traceback (most recent call last):
  File "/Users/Kev0/oak/repos/depthai-python/examples/StereoDepth/rgb_depth_aligned.py", line 33, in <module>
    device = dai.Device()
RuntimeError: Failed to find device after booting, error message: X_LINK_DEVICE_NOT_FOUND~~
So I cycled the device once more and AHA! 

https://user-images.githubusercontent.com/24589462/198404590-fd6d739e-3fb2-4cdc-accc-4d6165b26d18.mp4

So I then disconnected from the macbook and went back to the development system (windows 10), I am promptly greeted by the message: 
~~Traceback (most recent call last):
  File "J:\Research\AR Projects\depthai-python\examples\StereoDepth\rgb_depth_aligned.py", line 33, in <module>
    device = dai.Device()~~
So I cycled the device once more and it's now behaving completely normal...
