### ISSUE TITLE
[BUG] setStopStreaming at start gives [critical] Fatal error. Please report to developers. Log: 'PlgSrcMipi' '1109'

### ISSUE THREAD

**Issue by chengguizi** [luxonis/depthai-core#745]
**Describe the bug**
I am finding ways to start the pipeline but without starting all cameras' streaming at once. There is API of setStopStreaming and I know I could put them into initialControl.

However, There is a bug that cause [critical] Fatal error. Please report to developers. Log: 'PlgSrcMipi' '1109' , when I am trying on OV9282 sensor on FFC-4P board.

The same code has no error on a AR0234-inside OAK-D-LR unit

**Minimal Reproducible Example**

Hardware setup:
1. OAK-FFC-FP
2. 2 x OV9282 modules, mounted on CAMB and CAMC

Code (using latest develop branch python)
```
#!/usr/bin/env python3

import cv2
import depthai as dai
import time

# Create pipeline
pipeline = dai.Pipeline()

# Define sources and outputs
monoLeft = pipeline.create(dai.node.MonoCamera)
monoRight = pipeline.create(dai.node.MonoCamera)
xoutLeft = pipeline.create(dai.node.XLinkOut)
xoutRight = pipeline.create(dai.node.XLinkOut)

xoutLeft.setStreamName('left')
xoutRight.setStreamName('right')

# Properties
monoLeft.setBoardSocket(dai.CameraBoardSocket.LEFT)
monoLeft.setResolution(dai.MonoCameraProperties.SensorResolution.THE_720_P)
monoRight.setBoardSocket(dai.CameraBoardSocket.RIGHT)
monoRight.setResolution(dai.MonoCameraProperties.SensorResolution.THE_720_P)

controlIn = pipeline.create(dai.node.XLinkIn)
controlIn.setStreamName('control')
controlIn.out.link(monoRight.inputControl)
controlIn.out.link(monoLeft.inputControl)

# Linking
monoRight.out.link(xoutRight.input)
monoLeft.out.link(xoutLeft.input)

monoLeft.initialControl.setStopStreaming()
monoRight.initialControl.setStopStreaming()

# Connect to device and start pipeline
with dai.Device(pipeline) as device:

    controlQueue = device.getInputQueue('control')

    print("device started, wait 10 secs")
    time.sleep(10)

    print("starts camera stream now")
    ctrl = dai.CameraControl()
    ctrl.setStartStreaming()


    # Output queues will be used to get the grayscale frames from the outputs defined above
    qLeft = device.getOutputQueue(name="left", maxSize=4, blocking=False)
    qRight = device.getOutputQueue(name="right", maxSize=4, blocking=False)

    while True:
        # Instead of get (blocking), we use tryGet (non-blocking) which will return the available data or None otherwise
        inLeft = qLeft.tryGet()
        inRight = qRight.tryGet()

        if inLeft is not None:
            cv2.imshow("left", inLeft.getCvFrame())

        if inRight is not None:
            cv2.imshow("right", inRight.getCvFrame())

        if cv2.waitKey(1) == ord('q'):
            break

```

**Expected behavior**
Ability to stop at start, and resume correctly, with the API.

**Comment by chengguizi** [comment]
Run on OV9282 x 2:
```
(depthai-latest) ~/depthai/depthai-python-latest/depthai-python/examples/SetStreaming$ python3 start_paused.py 
device started, wait 10 secs
[18443010615BBD0F00] [3.8] [7.159] [system] [critical] Fatal error. Please report to developers. Log: 'PlgSrcMipi' '1109'
starts camera stream now
Traceback (most recent call last):
  File "start_paused.py", line 52, in <module>
    qLeft = device.getOutputQueue(name="left", maxSize=4, blocking=False)
ValueError: Device already closed or disconnected


```

Run on AR0234 x 2:
```

(depthai-latest) ~/depthai/depthai-python-latest/depthai-python/examples/SetStreaming$ python3 start_paused.py 
[1844301061DF5D1200] [3.8] [1.244] [MonoCamera(0)] [error] AR0234 only supports THE_1200_P resolution, defaulting to it
[1844301061DF5D1200] [3.8] [1.244] [MonoCamera(1)] [error] AR0234 only supports THE_1200_P resolution, defaulting to it
device started, wait 10 secs
starts camera stream now
^CTraceback (most recent call last):
  File "start_paused.py", line 65, in <module>
    if cv2.waitKey(1) == ord('q'):
KeyboardInterrupt

```

**Comment by chengguizi** [comment]
Related to #671 ?
